'use client';

import { useState } from 'react';
import { Sparkles, Send, Bot, CheckCircle2, AlertCircle } from 'lucide-react';
import { CollapsibleCard } from './CollapsibleCard';

interface AskAiModuleProps {
  sectionNumber: string;
}

export function AskAiModule({ sectionNumber }: AskAiModuleProps) {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const samplePrompts = [
    `Explain Section ${sectionNumber} eligibility criteria`,
    `What are the caps under Section ${sectionNumber}?`,
    `How does Section ${sectionNumber} interact with Sec 115BAC?`,
  ];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!question.trim()) return;

    setLoading(true);
    setAnswer(null);
    setErrorMsg(null);

    try {
      const res = await fetch('/api/ai/explain', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          query: question,
          sectionNumber,
        }),
      });

      const data = await res.json();

      if (!res.ok || !data.success) {
        if (data.error && data.error.includes('OPENROUTER_API_KEY')) {
          setErrorMsg('OPENROUTER_API_KEY is not configured. Please add it to your environment variables.');
        } else {
          setErrorMsg(data.error || 'Failed to get AI response.');
        }
        setLoading(false);
        return;
      }

      const geminiData = data.data;
      setAnswer(
        geminiData.simpleMeaning ||
        geminiData.bareActSummary ||
        `Section ${sectionNumber} guidance generated by Google Gemini AI.`
      );
    } catch {
      setErrorMsg('Network error while connecting to Gemini AI endpoint.');
    } finally {
      setLoading(false);
    }
  };

  const handleChipClick = (promptText: string) => {
    setQuestion(promptText);
  };

  return (
    <CollapsibleCard
      id="module-ask-ai"
      title="Ask AI Tutor"
      icon={Sparkles}
      badge={
        <span className="text-xs px-2.5 py-0.5 rounded-full bg-violet-500/20 text-violet-300 border border-violet-500/30 font-medium">
          Google Gemini AI
        </span>
      }
    >
      <div className="space-y-4 pt-2">
        {/* Sample prompt chips */}
        <div className="flex flex-wrap gap-1.5">
          {samplePrompts.map((p) => (
            <button
              key={p}
              type="button"
              onClick={() => handleChipClick(p)}
              className="text-xs px-3 py-1 rounded-full bg-white/5 border border-white/10 text-muted-foreground hover:text-foreground hover:bg-white/10 hover:border-violet-500/30 transition-all duration-150"
            >
              ✨ {p}
            </button>
          ))}
        </div>

        {/* Question Form */}
        <form onSubmit={handleSubmit} className="relative flex items-center">
          <input
            type="text"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder={`Ask Google Gemini AI any question about Section ${sectionNumber}…`}
            className="w-full px-4 py-3.5 pr-12 rounded-xl bg-white/5 border border-white/15 text-sm text-foreground placeholder:text-muted-foreground/60 outline-none focus:border-violet-500/60 focus:ring-2 focus:ring-violet-500/20 transition-all"
          />
          <button
            type="submit"
            disabled={loading || !question.trim()}
            aria-label="Send question to Gemini AI Tutor"
            className="absolute right-2 flex items-center justify-center w-8 h-8 rounded-lg bg-gradient-to-r from-blue-500 to-violet-600 text-white disabled:opacity-40 hover:scale-105 active:scale-95 transition-all"
          >
            {loading ? (
              <Sparkles size={15} className="animate-spin" />
            ) : (
              <Send size={14} />
            )}
          </button>
        </form>

        {/* Error message if API key missing */}
        {errorMsg && (
          <div className="p-3.5 rounded-xl border border-amber-500/30 bg-amber-500/10 text-amber-300 text-xs flex items-center gap-2">
            <AlertCircle size={15} className="shrink-0" />
            <span>{errorMsg}</span>
          </div>
        )}

        {/* Gemini Answer Box */}
        {answer && (
          <div className="p-4 rounded-xl border border-violet-500/30 bg-violet-500/10 space-y-2 animate-in fade-in duration-200">
            <div className="flex items-center gap-2 text-xs font-semibold text-violet-300">
              <Bot size={15} />
              <span>Google Gemini AI Tutor</span>
              <CheckCircle2 size={13} className="text-emerald-400 ml-auto" />
            </div>
            <p className="text-xs md:text-sm text-foreground/90 leading-relaxed">
              {answer}
            </p>
          </div>
        )}
      </div>
    </CollapsibleCard>
  );
}
